// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// drcrtwa_fit_cpp
List drcrtwa_fit_cpp(IntegerVector arm, IntegerVector unit, IntegerVector cluster_size, NumericMatrix X_censoring, NumericMatrix X_terminal, NumericMatrix X_recurrent, NumericVector final_time, IntegerVector final_status, List recurrent_times, IntegerVector recurrent_codes, NumericVector event_weights, int terminal_code, NumericVector horizons, IntegerVector n_grid, NumericVector prob0, NumericVector prob1, List target_weights, CharacterVector estimand_names, bool keep_influence, bool keep_nuisance);
RcppExport SEXP _DRCRTwa_drcrtwa_fit_cpp(SEXP armSEXP, SEXP unitSEXP, SEXP cluster_sizeSEXP, SEXP X_censoringSEXP, SEXP X_terminalSEXP, SEXP X_recurrentSEXP, SEXP final_timeSEXP, SEXP final_statusSEXP, SEXP recurrent_timesSEXP, SEXP recurrent_codesSEXP, SEXP event_weightsSEXP, SEXP terminal_codeSEXP, SEXP horizonsSEXP, SEXP n_gridSEXP, SEXP prob0SEXP, SEXP prob1SEXP, SEXP target_weightsSEXP, SEXP estimand_namesSEXP, SEXP keep_influenceSEXP, SEXP keep_nuisanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type arm(armSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type unit(unitSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cluster_size(cluster_sizeSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_censoring(X_censoringSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_terminal(X_terminalSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X_recurrent(X_recurrentSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type final_time(final_timeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type final_status(final_statusSEXP);
    Rcpp::traits::input_parameter< List >::type recurrent_times(recurrent_timesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type recurrent_codes(recurrent_codesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type event_weights(event_weightsSEXP);
    Rcpp::traits::input_parameter< int >::type terminal_code(terminal_codeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type horizons(horizonsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n_grid(n_gridSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prob0(prob0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prob1(prob1SEXP);
    Rcpp::traits::input_parameter< List >::type target_weights(target_weightsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type estimand_names(estimand_namesSEXP);
    Rcpp::traits::input_parameter< bool >::type keep_influence(keep_influenceSEXP);
    Rcpp::traits::input_parameter< bool >::type keep_nuisance(keep_nuisanceSEXP);
    rcpp_result_gen = Rcpp::wrap(drcrtwa_fit_cpp(arm, unit, cluster_size, X_censoring, X_terminal, X_recurrent, final_time, final_status, recurrent_times, recurrent_codes, event_weights, terminal_code, horizons, n_grid, prob0, prob1, target_weights, estimand_names, keep_influence, keep_nuisance));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DRCRTwa_drcrtwa_fit_cpp", (DL_FUNC) &_DRCRTwa_drcrtwa_fit_cpp, 20},
    {NULL, NULL, 0}
};

RcppExport void R_init_DRCRTwa(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
