# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Internal compiled fitting interface
#'
#' Low-level Rcpp entry point used by [DRCRT_WA()]. This function is an
#' implementation detail and is not part of the supported user interface.
#'
#' @param arm,unit,cluster_size Integer subject-level design vectors.
#' @param X_censoring,X_terminal,X_recurrent Numeric nuisance-model matrices.
#' @param final_time,final_status Subject-level closing times and status codes.
#' @param recurrent_times Recurrent-event histories by event type and subject.
#' @param recurrent_codes,event_weights Recurrent-event codes and weights.
#' @param terminal_code Integer terminal-event code.
#' @param horizons,n_grid Analysis horizons and integration-grid sizes.
#' @param prob0,prob1 Subject-level randomization probabilities.
#' @param target_weights,estimand_names Target-population weights and labels.
#' @param keep_influence,keep_nuisance Logical storage controls.
#'
#' @return An internal list of compiled estimates and nuisance-model results.
#' @keywords internal
drcrtwa_fit_cpp <- function(arm, unit, cluster_size, X_censoring, X_terminal, X_recurrent, final_time, final_status, recurrent_times, recurrent_codes, event_weights, terminal_code, horizons, n_grid, prob0, prob1, target_weights, estimand_names, keep_influence, keep_nuisance) {
    .Call(`_DRCRTwa_drcrtwa_fit_cpp`, arm, unit, cluster_size, X_censoring, X_terminal, X_recurrent, final_time, final_status, recurrent_times, recurrent_codes, event_weights, terminal_code, horizons, n_grid, prob0, prob1, target_weights, estimand_names, keep_influence, keep_nuisance)
}

