# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

drcrtwa_fit_cpp <- function(arm, unit, cluster_size, X_censoring, X_terminal, X_recurrent, final_time, final_status, recurrent_times, recurrent_codes, event_weights, terminal_code, horizons, n_grid, prob0, prob1, target_weights, estimand_names, keep_influence, keep_nuisance) {
    .Call('_DRCRTwa_drcrtwa_fit_cpp', PACKAGE = 'DRCRTwa', arm, unit, cluster_size, X_censoring, X_terminal, X_recurrent, final_time, final_status, recurrent_times, recurrent_codes, event_weights, terminal_code, horizons, n_grid, prob0, prob1, target_weights, estimand_names, keep_influence, keep_nuisance)
}

